/** @type {import('tailwindcss').Config} */
const colors = require('tailwindcss/colors');
const withMT = require('@material-tailwind/react/utils/withMT');



module.exports = withMT({
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        environmentR: ['EnvironmentR'],
      },
    },
    colors: {
      transparent: 'transparent',
      current: 'currentColor',
      black: colors.black,
      white: colors.white,
      gray: colors.gray,
      emerald: colors.emerald,
      indigo: colors.indigo,
      yellow: colors.yellow,
      slate: colors.slate,
      zinc: colors.zinc,
      neutral: colors.neutral,
      stone: colors.stone,
      red: colors.red,
      orange: colors.orange,
      amber: colors.amber,
      lime: colors.lime,
      green: colors.green,
      teal: colors.teal,
      cyan: colors.cyan,
      sky: colors.sky,
      blue: colors.blue,
      violet: colors.violet,
      fuchsia: colors.fuchsia,
      pink: colors.pink,
      rose: colors.rose,
      'chaeum-blue-100': '#e4ffff',
      'chaeum-blue-200': '#bbfbfc',
      'chaeum-blue-300': '#98f4f5',
      'chaeum-blue-400': '#66e7f3',
      'chaeum-blue-500': '#49d9e6',
      'chaeum-blue-600': '#37cedc',
      'chaeum-blue-700': '#2bb7c4',
      'chaeum-blue-800': '#0e98a4',
      'chaeum-blue-900': '#046d76',
      'chaeum-blue-990': '#014349',
      'chaeum-yellow-300': '#fffebe',
      'chaeum-yellow-500': '#fffe87',
      'chaeum-yellow-600': '#fffd3f',
      'chaeum-yellow-700': '#fffc00',
      'chaeum-lime-300': '#e8ffb0',
      'chaeum-lime-500': '#d1fb6b',
      'chaeum-lime-600': '#b5ff00',
      'chaeum-lime-700': '#a3e404',
      'chaeum-navy-300': '#0071c7',
      'chaeum-navy-500': '#005da4',
      'chaeum-navy-600': '#124a75',
      'chaeum-navy-700': '#003157',
      'chaeum-navy-900': '#002b4c',
      'chaeum-gray-300': '#d0d3de',
      'chaeum-gray-500': '#bbbec8',
      'chaeum-gray-600': '#989caf',
      'chaeum-gray-700': '#696d80',
      'chaeum-gray-900': '#45495b',
    },
  },
  plugins: [],
});
