spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/example?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ssafy
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 663642..
            client-secret: GOCSP...
            scope:
              - email
              - profile
jwt:
  issuer: jwt-issuer
  secret_key: jwt-secretkey